### ISSUE TITLE
DOB input size

### ISSUE THREAD

**Issue by lmmrssa** [earthowned/planetfarms#164]
DOB input field is out of size
![Screenshot 2021-05-06 130602](https://user-images.githubusercontent.com/2909490/117257704-e9ab8d80-ae6b-11eb-9533-ff29f9d59305.png)

Also when there is not prefix image on input it should not be consuming space for icon
![Screenshot 2021-05-06 130828](https://user-images.githubusercontent.com/2909490/117258089-4eff7e80-ae6c-11eb-8024-eacce1ed0afb.png)

**Comment by ABee-Tech** [comment]
Closed
