### ISSUE TITLE
Fresh install npx sequilize error

### ISSUE THREAD

**Issue by rjpadilla** [earthowned/planetfarms#355]
When running npx sequilize it causes error on fresh install.
```
== 20210712073151-alter-table-texts-add-column-textDesc: migrating =======
(node:3855) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: column "textDescription" of relation "texts" already exists
    at Query.formatError (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.addColumn (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:408:12)
(node:3855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
== 20210712073151-alter-table-texts-add-column-textDesc: migrated (0.018s)
```

**Comment by rjpadilla** [comment]
Another error found from running this command
```
== 20210627152703-alter-table-lessons-remove-column-steps: migrating =======
(node:3855) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: column "courseId" cannot be cast automatically to type integer
    at Query.formatError (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/sequelize.js:619:16
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3855) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: foreign key constraint "courseId_fkey_forLesson" cannot be implemented
    at Query.formatError (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.addConstraint (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:722:12)
(node:3855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
== 20210627152703-alter-table-lessons-remove-column-steps: migrated (0.066s)
```

**Comment by dogi** [comment]
> Another error found from running this command
> 
> ```
> == 20210627152703-alter-table-lessons-remove-column-steps: migrating =======
> (node:3855) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: column "courseId" cannot be cast automatically to type integer
>     at Query.formatError (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
>     at Query.run (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async /mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/sequelize.js:619:16
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:3855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:3855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:3855) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: foreign key constraint "courseId_fkey_forLesson" cannot be implemented
>     at Query.formatError (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
>     at Query.run (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async /mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/sequelize.js:619:16
>     at async PostgresQueryInterface.addConstraint (/mnt/c/Users/RJ/Desktop/treehouses/upstream-planetfarms/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:722:12)
> (node:3855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> == 20210627152703-alter-table-lessons-remove-column-steps: migrated (0.066s)
> ```

![image](https://user-images.githubusercontent.com/13684059/126269403-55b478f3-79ca-4f0d-bc62-68ffddcecb91.png)
courses and lesson table have connection
